### ISSUE TITLE
Potential issues when using hashCode for deployment equality checks

### ISSUE THREAD

**Issue by ltj** [cph-cachet/carp.core-kotlin#135]
https://github.com/cph-cachet/carp.core-kotlin/blob/e651599286b6b3dfe7e7c1886d2ecef8d1140d49/carp.deployment.core/src/commonMain/kotlin/dk/cachet/carp/deployment/domain/StudyDeployment.kt#L389

First off, it's a bit confusing we're calling it checkSum here when we really use the hashCode. It's an important distinction imho since checksum typically can be used for object equality with very little risk of collisions (depending on algorithm).

A hashCode on the other hand, (by the typical contract) must be the same for two equal objects, but can both _different or the same_  for unequal objects. And since the key space is limited to `int` it's not unlikely that two unequal objects will yield the same hashCode. Thus it's not good fit for object equality which is a requirement here.

Furthermore I'm worried that the generated hashCode function by kotlin MP is not _exactly_ the same for all targets. This has not been verified though.

**Comment by Whathecode** [comment]
Did you encounter a bug in relation to this, or you just ran into and noticed this as a bug?

I agree it is, albeit a very rare one given the smallish size of redeployments we expect. Regardless, I should have left a todo item or issue here, so thank you!

I doubt the hashcode calculation would be different across platforms, however.

**Comment by ltj** [comment]
The hashcode _is_ different across platforms and it is highly discouraged to rely on identical hashcodes being generated in distributed systems.

With that said, there just might still be issues related to how the object is marshalled in and out of repositories and across the wire. We must fix this anyway. But we must also come up with a better fingerprinting solution. I'm looking into a pure Kotlin SHA256 digest right now
