### ISSUE TITLE
java.time.Instant isn't supported on Android API versions below 26

### ISSUE THREAD

**Issue by patrickusiewicz** [cph-cachet/carp.core-kotlin#136]
I have run into an issue with initializing a StudyProtocol on Android API below 26. `StudyProtocol.creationDate` is of type `java.time` which isn't supported on Android API versions below 26. It is nativaly supported on Android API 26+. It is possible to add 'java.time' support to Android API below 26, by using Android Gradle Plugin 4.0.0+, see [link](https://developer.android.com/studio/write/java8-support), instead of bumping android.minSdkVersion to 26. I have follwed the steps from the link, but then a new issue occurs because of a check in `Immutable` JVM class. The classifier of a property of type `java.time.Instant` (see `StudyProtocol.creationDate`) is null. I haven't looked into why it is null, but I can confirm that it isn't null if I run the same code on a Android API 26+ device. But my last issue should be resolved when [issue 93](https://github.com/cph-cachet/carp.core-kotlin/issues/93) is fixed. 

As it is right know it isn't possible to create a StudyProtocol on Android devices running Android API below 26.

I have created a [branch](https://github.com/cph-cachet/carp.core-kotlin/tree/java-time-instant-android-issue) which show cases the issues with `java.time`. Run the instrumentation test, found in the two android modules' `androidTest` folders on an emulator with Android API pre 26.

**Comment by patrickusiewicz** [comment]
You need to have stable Android Studio 4.0.0+ to run the tests, because the project uses Android Gradle Plugin 4.0.0, see [](https://youtrack.jetbrains.com/issue/IDEA-233929).

**Comment by Whathecode** [comment]
Does this have priority for the current milestone?

**Comment by patrickusiewicz** [comment]
A reminder to be fixed after our milestone 🙂

**Comment by Whathecode** [comment]
Since immutability is no longer checked at runtime, this should be fixed in SNAPSHOT and in the next release: https://github.com/cph-cachet/carp.core-kotlin/pull/149

**Comment by patrickusiewicz** [comment]
Have you verified this issue with the latest SNAPSHOT?

**Comment by Whathecode** [comment]
No, but the `Immutable` class is entirely gone, so it is impossible for it to throw exceptions at runtime. :)

**Comment by patrickusiewicz** [comment]
Ok I will run the tests from https://github.com/cph-cachet/carp.core-kotlin/tree/java-time-instant-android-issue branch with the latest changes from `develop` branch.

**Comment by Whathecode** [comment]
Although the `Immutable` base class no longer exists, there still seems to be an issue remaining with `Instant`. Reopened until @patrickusiewicz finds out more.

**Comment by patrickusiewicz** [comment]
I cannot reproduce the issue anymore, you can close it.
