### ISSUE TITLE
Rename domain objects prior to 1.0.0 stable release

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#146]
Several domain objects are under consideration to be renamed:

- `master device descriptor` could either become `hub device descriptor` or `primary device descriptor`.
- `study protocol` might become `study methodology`.

Before the 1.0.0 stable release where we lock in an interface, we should finalize these choices.

**Comment by bardram** [comment]
I tend to disagree to this - I like the names as is.

**Comment by bardram** [comment]
Some ideas / observations noted:

 * In a `StudyProtocol` the task is a `TaskDescriptor` and a device is a `DeviceDescriptor` -- but a trigger is just `Trigger` and a trigger task `TriggerTask` -- when is a `Descriptor` used?

**Comment by Whathecode** [comment]
There has also been a recurring question on how to name some of the plurals in the APIs. E.g. [in a recent PR](https://github.com/cph-cachet/carp.core-kotlin/pull/329/files/326dc74f778b25e82a15730cd0d1513437920f2b#r752260893).

What is the plural of "participant status", "device status", or "device registration status", etc? This is a bit inconsistent atm, we use both `<noun>List`, as well as `<nouns>Status`. And there is some consensus `<noun>Statuses` sounds odd, albeit correct.

Should we pick one approach and just stick with it?

**Comment by Whathecode** [comment]
Should `ParticipantData` which is stored in the deployment subsystem be renamed to `DeploymentData` to disambiguate it from anticipated `ParticipantData` in the studies subsystem.
