### ISSUE TITLE
Rename `Deployment` to `StudyDeployment`?

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#25]
Currently `Deployment` in the Deployment subsystem is _"[a] single instantiation of a `StudyProtocol`, taking care of common concerns when 'running' a study. I.e., a `Deployment` is responsible for registering the physical devices described in the `StudyProtocol`, enabling a connection between them, tracking device connection issues, assessing data quality, and registering participant consent."_

Now, we need a `DeviceDeployment`, which contains all the necessary information for a study to run on one particular device part of the overall study setup. I have referred to this previously as 'device configuration', I believe, among other names.

Perhaps it is a good idea to better disambiguate between the two by calling the former `StudyDeployment`?

**Comment by davidwadge** [comment]
Makes sense to me.

**Comment by Whathecode** [comment]
Renamed in https://github.com/cph-cachet/carp.core-kotlin/commit/fded47dc4fb84436ef42adb1f612b48ad830ca3e
