### ISSUE TITLE
Upgrade Gradle

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#344]
Try upgrading Gradle to see whether it has an impact on JS IR backend code generation.

**Comment by patrickusiewicz** [comment]
What impact are you talking about?

In general, updating to Gradle 7 does have benefits:
- https://gradle.org/whats-new/gradle-7/
- [upgrade check for Log4J](https://docs.gradle.org/7.3.3/release-notes.html)

**Comment by Whathecode** [comment]
> What impact are you talking about?

We're struggling using the publication IR JS artifacts. See links to relevant discussions here: https://github.com/cph-cachet/carp.core-kotlin/issues/156#issuecomment-999779615

I tried upgrade to latest Gradle in the meantime on that branch, and it didn't make a difference.
