### ISSUE TITLE
Add informed consent input data type

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#450]
We require informed consent as a new input data types that could be implemented in core, the specifications are copied from here: https://github.com/cph-cachet/carp.sensing-flutter/blob/develop-1.1.0/carp_core/lib/common/application/input_data.dart

**Informed consent**
 ```dart
  /// The time this informed consent was signed.
  DateTime signedTimestamp;

  /// The location where this informed consent was signed.
  String? signedLocation;

  /// The ID of the participant who signed this consent.
  String? userID;

  /// The full name of the participant who signed this consent.
  String name;

  /// The content of the signed consent.
  ///
  /// This may be plain text or JSON.
  String? consent;

  /// The image of the provided signature in png format as bytes.
  String? signatureImage;
```

**Comment by bardram** [comment]
We have decided to add the IC as part of the study protocol. This will then be downloaded as part of the deployment for a participant. 

We have also decided to upload the IC as participant data with a specific input type. This is much more simple and can be done with the existing CARP Core implementation. In addition, we would not need to change the database structure in a running deployment.

If someone has the time and skills to implement a full-blown informed consent model i CARP Core, we will migrate to this later.
