### ISSUE TITLE
Extend a study to know which researchers can access it

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.core-kotlin#481]
Right now the study only has an `ownerId` tag that tells which research owns the study. But there might be several researchers who need to access and/or modify it, so we need a list of `accessIds` or similar.

**Comment by Whathecode** [comment]
I think the original idea was that `ownerId` can be a single individual, or group, as decided by the infrastructure. Access management is an infrastructure concern. If the infrastructure wants to allow multiple people to have access, nothing really prevents the infrastructure from mapping a `ownerId` to a group of participants.

```
    /**
     * The ID of the entity (e.g., person or group) that created this [Study].
     */
    val ownerId: UUID,
```

**Comment by bardram** [comment]
Not part of core - move to CAWS.
