### ISSUE TITLE
Why am I getting all invitations, incl. the ones not assigned to me?

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.core-kotlin#482]
I have made a family study with a father and a mother, and made a deployment with assignments to users like this:

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/d380a8e1-16c6-4f13-bedc-a2850120c3f3">

So - Jakob is the "Mother" and Aamir is the "Father".

However, when I authenticate to CAWS as "Jakob" (jakob@bardram.net), I get the following invitations from the ParticipationService:

```json
[
    {
        "participation": {
            "studyDeploymentId": "58ce18ff-40e3-4cd0-9fba-fc893d784891",
            "participantId": "264bf3dc-b6c8-4252-b44e-2c5e00262ce9",
            "assignedRoles": {
                "__type": "dk.cachet.carp.common.application.users.AssignedTo.Roles",
                "roleNames": [
                    "Mother"
                ]
            }
        },
        "invitation": {
            "name": "Family Study w. Participant Data",
            "applicationData": "d6d047d5-4cfd-479b-87ac-99f4b5fee172"
        },
        "assignedDevices": [
            {
                "device": {
                    "__type": "dk.cachet.carp.common.application.devices.Smartphone",
                    "roleName": "Mother's Phone",
                    "isPrimaryDevice": true
                }
            }
        ]
    },
    {
        "participation": {
            "studyDeploymentId": "58ce18ff-40e3-4cd0-9fba-fc893d784891",
            "participantId": "5b486d25-b75e-4116-9a4f-eea8105ceea0",
            "assignedRoles": {
                "__type": "dk.cachet.carp.common.application.users.AssignedTo.Roles",
                "roleNames": [
                    "Father"
                ]
            }
        },
        "invitation": {
            "name": "Family Study w. Participant Data",
            "applicationData": "d6d047d5-4cfd-479b-87ac-99f4b5fee172"
        },
        "assignedDevices": [
            {
                "device": {
                    "__type": "dk.cachet.carp.common.application.devices.Smartphone",
                    "roleName": "Father's Phone",
                    "isPrimaryDevice": true
                }
            }
        ]
    },
]
```

So - even though I autheticate as the "Mother" I get **BOTH** invitations????

This entails, that I (as a participant) could choose to be the Father, even though the researcher has assigned me the Mother role......

**Comment by Whathecode** [comment]
This could also be a CAWS bug. Let's have a look whether we have proper coverage of the Core part of this logic ...

[Seemingly not](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.deployments.core/src/commonTest/kotlin/dk/cachet/carp/deployments/application/ParticipationServiceTest.kt#L55). It should be worthwhile adding a more complex invitation test here similar to the scenario you describe.

Maybe a suitable small task for @yuanchen233 ? That way we can more easily determine whether it is CAWS or Core.

**Comment by bardram** [comment]
@Whathecode - I'm a bit confused. Is this a bug in Core or CAWS? Above you point to a test case, but this doesn't reveal (at least to me) if something has to be "fixed" in Core.

**Comment by Whathecode** [comment]
The code was sufficiently complex I couldn't quickly/easily rule it out as a core bug. It's missing test coverage to do so. I haven't looked into more detail.

So best approach is adding such a test so we have future coverage, and we'll know whether it is core or CAWS. :)

**Comment by yuanchen233** [comment]
We don't have test case covering  this scenario, thus can not tell if this is something need to be fixed in Core. I can look into this next.

But, the description for [getActiveParticipationInvitations](https://github.com/cph-cachet/carp.core-kotlin/blob/f4c3994dc2371c12a43f5fc5e637a7e344099370/carp.deployments.core/src/commonMain/kotlin/dk/cachet/carp/deployments/application/ParticipationService.kt#L33) states 'all participations', so does this imply this result is expected?

**Comment by Whathecode** [comment]
> But, the description for [getActiveParticipationInvitations](https://github.com/cph-cachet/carp.core-kotlin/blob/f4c3994dc2371c12a43f5fc5e637a7e344099370/carp.deployments.core/src/commonMain/kotlin/dk/cachet/carp/deployments/application/ParticipationService.kt#L33) states 'all participations', so does this imply this result is expected?

It does qualify:

> .... the account with the given [accountId] has been invited to.

So, it shouldn't return participations from other account IDs. ;)

**Comment by yuanchen233** [comment]
I wrote a simple test case and Core implementation works as expected,
this bug is caused by CAWS implementation of `ParticipationRepository.getParticipationInvitations`.
More specifically, `participations` from all `participantGroup` should be flattened before filter by `accountId`, otherwise it will return all participations within a participant group which contains that `accountId`.

**Comment by Whathecode** [comment]
Thank you @yuanchen233 Feel free to create a PR for the test case. It would still be relevant for core.

Reassigned this as an "enhancement" (providing test coverage) rather than a bug.

**Comment by bardram** [comment]
I just tested this on the new DEV deployment and now I only get the invitations I am supposed to get.

**Comment by yuanchen233** [comment]
> Thank you @yuanchen233 Feel free to create a PR for the test case. It would still be relevant for core.

Sure and thanks, I wanted to see if there are other situations/test cases can benefit from a more complex participant group as well, but didn't find anything right away. If this scenario can be re-used for testing other modules, I'll add it to `createTestObject`.
