### ISSUE TITLE
Use singular/plural form consistently in module and package names

### ISSUE THREAD

**Issue by ltj** [cph-cachet/carp.core-kotlin#56]
_deployment_ but protocol**s** and studie**s**

Maybe it's nitpicking but I think the singular form should be used consistently :)

**Comment by Whathecode** [comment]
This impact the artifact name on Maven. Therefore, if we carry this change through, I suggest we do so once we release a first stable release.

During alpha development now I will just continue using the same artifact names.

**Comment by Whathecode** [comment]
The current line of thinking is to use plural.
