### ISSUE TITLE
How to deal with failed device deployments?

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#58]
What if registration succeeds for a given device in a study deployment, but deployment fails since not all required plugins are available? The user might want to update the client application, or possibly even use a different phone so that device deployment might succeed.

Currently, we only allow registering a device once. Thus, the registration will succeed and be stored on the server side. Any registration for the same device in the study deployment after will fail.

This is by design, since 'reregistering' devices might cause discrepancies between the 'contact information' sent to a dependent device and the one that is eventually registered.

Should we think of incorporating some 'reset' logic for study deployments?

**Comment by ltj** [comment]
@Whathecode in terms of the different scenarios:

1. Missing "plugins": Should the client not check this prior to registering itself as a master device?
2. App ugrade: Runtime is retained in app data between upgrades. If the app has just registered itself in a deployment, and the user then exits and upgrades the app it _should_ be able to continue from this point
3. New phone: I'd say this would require a new deployment unless there's still a free registration slot. Whether a new deployment can be client initiated, automated in the backend or simply requires manual intervention in the study manager is up for discussion

**Comment by Whathecode** [comment]
This will be resolved in https://github.com/cph-cachet/carp.core-kotlin/pull/117
