### ISSUE TITLE
Transition to kotlinx.serialization runtime 0.14

### ISSUE THREAD

**Issue by ltj** [cph-cachet/carp.core-kotlin#81]
Sealed class serializer and it's implicit polymorphic ditto is desired downstream but carp currently blocks this via it's implicit dependency of now-deprecated UnionKind (sealed and polymorphic kinds now uses PolymorphicKind)

Ktor serialization also uses the v0.14 runtime now, so this also blocks upgrade to ktor 1.2.6

**Comment by Whathecode** [comment]
This is resolved already in the snapshot release: https://github.com/cph-cachet/carp.core-kotlin/commit/d9d19ecbc5fbeb00defb71fd89e3a47820aaee86
