### ISSUE TITLE
DateTime toString method needs to be properly defined

### ISSUE THREAD

**Issue by pekkr** [cph-cachet/carp.core-kotlin#92]
Currently, toString looks like this: dk.cachet.carp.common.DateTime@31fffe78

**Comment by Whathecode** [comment]
Fixed for now in https://github.com/cph-cachet/carp.core-kotlin/commit/ed2a3f5ce1dbc9315c37669350467171ee653d52

But, the more functionality we need out of `DateTime`, the more we should considering using a separate library instead: https://github.com/cph-cachet/carp.core-kotlin/issues/95
